spring:
  application:
    name: order
  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
        registerHealthIndicator: true
        recordFailurePredicate: app.global.config.RestTemplateCircuitRecordFailurePredicate

    instances:
      default:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 6s
        cancelRunningFuture: true

server:
  port: 8084
