spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_NAME}?tls=true&tlsCAFile=/app/global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

      ssl:
        enabled: true
        trust-store: /app/certs/truststore.jks # Docker 컨테이너 내부 경로
        trust-store-password: Goorm3project # Dockerfile에서 설정한 암호

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI}

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE}

discord:
  webhook:
    url: ${DISCORD_URL}

service:
  store:
    url: ${STORE_SVC_URI}

redis:
  refund:
    queue: ${REDIS_REFUND_QUEUE}
