spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_platform}
    username: ${DB_USERNAME:bonun}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      protocol: ${REDIS_PROTOCOL:redis://}
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      database: 0
    mongodb:
      host: ${MONGODB:localhost}
      port: 27017
      database: ${MONGO_NAME:store-db}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:profectcloud}
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8083/oauth/jwks}


  kafka:
    bootstrap-servers:
      - ${KAFKA_URL1:localhost:9092}
      - ${KAFKA_URL2:localhost:9094}
      - ${KAFKA_URL3:localhost:9096}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable-idempotence: true
      retries: 2
      acks: all
      properties:
        max.in.flight.requests.per.connection: 3
        min.insync.replicas: 2
    admin:
      auto-create: true

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE:internal-services}

discord:
  webhook:
    url: ${DISCORD_URL:https://discord.com/api/webhooks/1406866286629355540/Y4r06Y2UIA5IjkrG_JqWC1P_u0xC9GuTmdR0N-ji6eQiuNDsyu_wToA0RcEAjhlWpSEU}

service:
  store:
    url: ${STORE_SVC_URI:http://localhost:8082}

redis:
  refund:
    queue: ${REDIS_REFUND_QUEUE}

topics:
  order:
    create_requested: order.valid.request
    validated: order.valid.result
    canceled: refund.request
    approve: order.approve.result
    completed: order.completed
    dev:
      completed: dev.order.completed
  payment:
    result: payment.result
  stock:
    request: stock.request
    result: stock.result
