spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # data:
  #   redis:
  #     host: ${REDIS_HOST}
  #     port: ${REDIS_PORT}
  #     password: ${REDIS_PASSWORD}

data:
  mongodb:
    uri:
      mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGODB}:${MONGO_PORT}/${MONGO_NAME}?ssl=true&replicaSet=rs0&retryWrites=false
    ssl:
      enabled: true
      trust-store: /app/certs/truststore.jks # Docker 컨테이너 내부 경로
      trust-store-password: Goorm3project # Dockerfile에서 설정한 암호

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI}

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE}

discord:
  webhook:
    url: "https://discord.com/api/webhooks/1406866286629355540/Y4r06Y2UIA5IjkrG_JqWC1P_u0xC9GuTmdR0N-ji6eQiuNDsyu_wToA0RcEAjhlWpSEU"

service:
  store:
    url: ${STORE_SVC_URI}
