spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_NAME}?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: ${MONGO_NAME}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI}

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE}

discord:
  webhook:
    url: ${DISCORD_URL}

service:
  store:
    url: ${STORE_SVC_URI}

redis:
  refund:
    queue: ${REDIS_REFUND_QUEUE}
